### ISSUE TITLE
安裝 rubocop

### ISSUE THREAD

**Issue by kakas** [kakas/astro_camp_traning#1]
https://github.com/rubocop-hq/rubocop-rails

.rubocop.yml
```yml
require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*.rb'
```
